"use client";
import{ArrowDown,ArrowRight,BadgeCheck,CalendarDays,CarFront,CircleDollarSign,Clock3,MapPin,MessageCircle,Phone,Search,ShieldCheck,Sparkles,Truck,Wrench}from"lucide-react";
import{useMemo,useState}from"react";import Header from"@/components/Header";import CarCard from"@/components/CarCard";import RevealObserver from"@/components/RevealObserver";import VehicleSearch,{Filters}from"@/components/VehicleSearch";import BrandRail from"@/components/BrandRail";import ContactForm from"@/components/ContactForm";import{cars}from"@/data/cars";import{brands}from"@/data/brands";import{useLanguage}from"@/components/LanguageProvider";
const types=[
["SUV","Space, power and comfort.","Hapësirë, fuqi dhe rehati.","https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=85"],
["Sedan","Elegance for every journey.","Elegancë për çdo rrugëtim.","https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=1200&q=85"],
["Coupé","A design that never goes unnoticed.","Dizajn që nuk kalon pa u vënë re.","https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=85"],
["Electric","Performance of the future.","Performancë e së ardhmes.","https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=85"]];
export default function Home(){const{lang}=useLanguage();const sq=lang==="sq";const[filters,setFilters]=useState<Filters>({query:"",brand:"",model:"",maxPrice:null});const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();const filtered=useMemo(()=>cars.filter(c=>{const brandName=brands.find(b=>b.slug===filters.brand)?.name;const price=Number(c.price.replace(/[^0-9]/g,""));const haystack=normalize(`${c.brand} ${c.model}`);const words=normalize(filters.query).split(/\s+/).filter(Boolean);return words.every(word=>haystack.includes(word))&&(!brandName||normalize(c.brand)===normalize(brandName))&&(!filters.model||normalize(c.model).includes(normalize(filters.model)))&&(!filters.maxPrice||price<=filters.maxPrice)}),[filters]);const runSearch=()=>setTimeout(()=>document.getElementById("veturat")?.scrollIntoView({behavior:"smooth"}),40);const resetAll=()=>setFilters({query:"",brand:"",model:"",maxPrice:null});
const t=(a:string,b:string)=>sq?a:b;return <main><RevealObserver/><Header/>
<section id="ballina" className="hero"><video className="hero-video" autoPlay muted loop playsInline poster="https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=2200&q=90"><source src="https://videos.pexels.com/video-files/5309381/5309381-hd_1920_1080_25fps.mp4" type="video/mp4"/></video><div className="hero-overlay"/><div className="hero-glow"/><div className="hero-content"><div className="hero-kicker"><span/> AUTO SALONI VETURA IME</div><h1>{t("Çdo rrugëtim fillon me ","Every journey begins with ")}<em>{t("veturën e duhur.","the right car.")}</em></h1><p>{t("Eksploroni vetura të përzgjedhura me kujdes, specifikime të detajuara dhe shërbim të ndërtuar mbi besim.","Explore carefully selected vehicles, detailed specifications, and service built on trust.")}</p><div className="hero-buttons"><a className="button" href="#veturat">{t("Shiko veturat","View cars")} <ArrowRight size={18}/></a><a className="button button--ghost" href="https://wa.me/38344000000" target="_blank" rel="noreferrer">WhatsApp <MessageCircle size={18}/></a></div></div><a className="scroll-hint" href="#search"><span>{t("Eksploro","Explore")}</span><ArrowDown size={18}/></a></section>
<section id="search" className="search-wrap"><VehicleSearch filters={filters} onChange={setFilters} onSearch={runSearch} onReset={resetAll}/></section>
<section id="veturat" className="section"><div className="section-head reveal"><div><span className="section-label">{t("KOLEKSIONI YNË","OUR COLLECTION")}</span><h2>{t("Vetura të ","Featured ")}<em>{t("veçuara","cars")}</em></h2></div><p>{t("Zbuloni modele të përzgjedhura që bashkojnë performancën, komoditetin dhe prezencën.","Discover selected models combining performance, comfort, and presence.")}</p><button className="text-button" onClick={resetAll}>{t("Shiko të gjitha","View all")} <ArrowRight size={17}/></button></div><p className="results-count">{filtered.length} {t("vetura u gjetën","cars found")}</p>{filtered.length?<div className="car-grid">{filtered.map(c=><CarCard key={c.id} car={c}/>)}</div>:<div className="empty-state"><Search/><h3>{t("Nuk u gjet asnjë veturë","No cars found")}</h3><p>{t("Provoni filtra të tjerë ose pastroni kërkimin.","Try different filters or reset your search.")}</p></div>}</section>
<BrandRail/>
<section className="section"><div className="section-head reveal"><div><span className="section-label">{t("GJENI STILIN TUAJ","FIND YOUR STYLE")}</span><h2>{t("Eksploro sipas ","Explore by ")}<em>{t("kategorisë","category")}</em></h2></div><p>{t("Nga SUV-të e fuqishme te sedanët elegantë—gjeni formatin që përshtatet me jetën tuaj.","From powerful SUVs to elegant sedans—find the format that fits your life.")}</p></div><div className="type-grid">{types.map(([name,en,sqdesc,image],i)=><a key={name} className={`type-card reveal ${i===0?"type-card--large":""}`} style={{backgroundImage:`linear-gradient(180deg,transparent 20%,rgba(5,6,7,.9)),url(${image})`}} href="#veturat"><div><span>0{i+1}</span><h3>{name}</h3><p>{sq?sqdesc:en}</p></div><ArrowRight/></a>)}</div></section>
<section id="rreth-nesh" className="statement"><div className="statement-image reveal"/><div className="statement-copy reveal"><span className="section-label">{t("RRETH NESH","ABOUT US")}</span><h2>{t("Më shumë se një veturë. ","More than a car. ")}<em>{t("Një zgjedhje me besim.","A choice built on trust.")}</em></h2><p>{t("Çdo veturë në koleksionin tonë përzgjidhet duke vlerësuar cilësinë, gjendjen dhe vlerën që i ofron pronarit të ardhshëm.","Every vehicle in our collection is selected for its quality, condition, and value to its next owner.")}</p><div className="statement-points"><span><BadgeCheck/> {t("Prezantim transparent","Transparent presentation")}</span><span><ShieldCheck/> {t("Cilësi e verifikuar","Verified quality")}</span><span><Sparkles/> {t("Përvojë premium","Premium experience")}</span></div><a className="text-link" href="#kontakti">{t("Mëso më shumë","Learn more")} <ArrowRight size={18}/></a></div></section>
<section id="sherbimet" className="section"><div className="center-head reveal"><span className="section-label">{t("SHËRBIMET","SERVICES")}</span><h2>{t("Gjithçka që ju duhet, ","Everything you need, ")}<em>{t("në një vend","in one place")}</em></h2><p>{t("Një proces i thjeshtë dhe profesional, nga kërkimi deri te dorëzimi.","A simple, professional process from search to delivery.")}</p></div><div className="service-grid">{[[CarFront,t("Shitja e veturave","Vehicle sales"),t("Koleksion i përzgjedhur me prezantim të plotë.","A selected collection with complete presentation.")],[CircleDollarSign,t("Financim & leasing","Financing & leasing"),t("Zgjidhje fleksibile sipas nevojave tuaja.","Flexible solutions for your needs.")],[Wrench,t("Ndërrimi i veturës","Trade-in"),t("Vlerësim fillestar për veturën që posedoni.","Initial valuation of your current vehicle.")],[Truck,t("Dorëzim në Kosovë","Delivery in Kosovo"),t("Transport i organizuar në qytetin tuaj.","Organized transport to your city.")],[CalendarDays,t("Rezervo vizitën","Book a visit"),t("Zgjidhni kohën më të përshtatshme për ju.","Choose the most convenient time.")],[Search,t("Kërkim me porosi","Vehicle sourcing"),t("Na tregoni modelin dhe ne e kërkojmë për ju.","Tell us the model and we will source it.")]].map(([Icon,title,text],i)=>{const I=Icon as typeof CarFront;return <article className="service-card reveal" style={{transitionDelay:`${i*50}ms`}} key={String(title)}><span><I/></span><h3>{String(title)}</h3><p>{String(text)}</p><a href="#kontakti">{t("Më shumë","More")} <ArrowRight size={16}/></a></article>})}</div></section>
<section className="trade"><div className="trade-inner reveal"><div><span className="section-label">TRADE-IN</span><h2>{t("Dëshironi ta ndërroni ","Would you like to trade in ")}<em>{t("veturën tuaj?","your car?")}</em></h2><p>{t("Na dërgoni informacionet bazë dhe ekipi ynë do t’ju kontaktojë për një vlerësim fillestar.","Send us the basic information and our team will contact you with an initial valuation.")}</p></div><a className="button" href="https://wa.me/38344000000" target="_blank" rel="noreferrer">{t("Kërko vlerësim","Request valuation")} <ArrowRight size={18}/></a></div></section>
<section className="stats"><div><strong>20+</strong><span>{t("Vetura në koleksion","Cars in collection")}</span></div><div><strong>10+</strong><span>{t("Marka premium","Premium brands")}</span></div><div><strong>100%</strong><span>{t("Përkushtim ndaj klientit","Customer commitment")}</span></div><div><strong>24h</strong><span>{t("Përgjigje e shpejtë","Fast response")}</span></div></section>
<section id="kontakti" className="contact"><div className="contact-copy reveal"><span className="section-label">{t("NA VIZITONI","VISIT US")}</span><h2>{t("Vetura juaj e ardhshme ","Your next car ")}<em>{t("ju pret.","is waiting.")}</em></h2><p>{t("Ejani në showroom ose kontaktoni ekipin tonë për çdo pyetje rreth koleksionit.","Visit our showroom or contact our team with any questions about the collection.")}</p><div className="contact-list"><a href="tel:+38344000000"><Phone/><span><small>{t("Telefon","Phone")}</small>+383 44 *** ***</span></a><a href="https://wa.me/38344000000" target="_blank" rel="noreferrer"><MessageCircle/><span><small>WhatsApp</small>{t("Na shkruani direkt","Message us directly")}</span></a><div><MapPin/><span><small>{t("Lokacioni","Location")}</small>{t("Prishtinë, Kosovë","Pristina, Kosovo")}</span></div><div><Clock3/><span><small>{t("Orari","Hours")}</small>{t("Hën–Sht, 09:00–18:00","Mon–Sat, 09:00–18:00")}</span></div></div></div><div className="contact-form reveal"><span className="form-title">{t("Kërko informacion","Request information")}</span><ContactForm/></div></section>
<footer><div className="footer-top"><a className="brand" href="#ballina"><span className="brand-mark">V</span><span><b>VETURA IME</b><small>AUTO SALONI</small></span></a><p>{t("Çdo rrugëtim fillon me veturën e duhur.","Every journey begins with the right car.")}</p><a className="footer-whatsapp" href="https://wa.me/38344000000" target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp</a></div><div className="footer-bottom"><span>© 2026 Auto Saloni Vetura Ime. {t("Website demonstrues.","Demo website.")}</span><div><a href="mailto:info@veturaime.com">{t("Privatësia","Privacy")}</a><a href="mailto:info@veturaime.com">{t("Kushtet","Terms")}</a><a href="#ballina">{t("Kthehu lart ↑","Back to top ↑")}</a></div></div></footer></main>}
